# gameroom_story/session.py — orchestration: start/act/end, prompt
# registration, chat activation. One active story per chat; the chat IS the
# playthrough. (Moved from the story_engine plugin 2026-08-03 — the game-room
# host owns both gears now; prompt pack registers under game-room.)
import json
import logging
import threading
import time
from pathlib import Path

from . import rooms, state as st, referee, render

logger = logging.getLogger(__name__)

_PLUGIN_DIR = Path(__file__).parent.parent
PLUGIN_NAME = "game-room"

# The referee's function module as the core registry names it — unioned into
# any toolset via the chat's `extra_toolsets` list (the "include story tools"
# checkbox). Story default: toolset 'none' + this (Krem's ruling 2026-08-03).
STORY_TOOLS_MODULE = "plugin_game-room_story_tools"

# The dual-layer GM conduct (Krem's ruling 2026-08-03: NO hidden
# instructions — conduct is user-editable and shows in the 👁 preview).
# Layer 1: this universal GM style, shared by ALL stories, toggleable per
# story. Layer 2: a per-story DM guide the pack ships, user override wins.
UNIVERSAL_GM_DEFAULT = (
    "We run this story as a team: the player drives their character; I bring the world "
    "and everyone else in it. Every turn I make sure the player knows what's around us "
    "and what they can do — exits, objects, people worth talking to — woven into my "
    "narration, not a menu. I use story_act to resolve actions: the player's when they "
    "choose them, my own character's small moves when it's natural — but I never spend "
    "the player's big choices for them or push us onward before they've had their say. "
    "I assist their intent, faithfully: when their wording is a SYNONYM for a declared "
    "verb ('drink the champagne' where the room says 'toast' — same act, different word), "
    "I use the declared verb on their behalf. But when their intent is genuinely DIFFERENT "
    "from everything declared (throwing the bracelet into the sea is not returning it), I "
    "never force a mapping — off-script acts are welcome: I play them out in the narration, "
    "honestly, with consequences in the fiction, and the tracked world simply doesn't "
    "change. Better an improvised scene than a betrayed intent. "
    "The engine referees; I narrate its verdicts truthfully and keep the machinery invisible. "
    "Each turn, a bracketed 'system context' block arrives alongside the player's message — "
    "that is my own app's dashboard (time, story state, room details), generated by my "
    "system, not written by the player and not an outside voice. I expect it, I trust it, "
    "and I never mistake it for a trick.")

_cfg_store = None

# One lifecycle op at a time. start/end/set_mode each read active.json,
# rename a journal, and re-register a prompt — a double-clicked ▶ Start ran
# two of those interleaved and the second archived the journal the first had
# just created (finding 4.12). Cheap: these are user-paced operations.
_lifecycle_lock = threading.RLock()


def _store():
    global _cfg_store
    if _cfg_store is None:
        # Loader singleton — a bare PluginState here would be a second
        # whole-file snapshot fighting gameroom_core's (finding 0.3).
        from core.plugin_loader import plugin_loader
        _cfg_store = plugin_loader.get_plugin_state(PLUGIN_NAME)
    return _cfg_store


def _as_bool(v, default=True):
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    return str(v).strip().lower() not in ("false", "0", "no", "off", "")


def conduct_for(story):
    """(universal_text | None, dm_guide | None) — the two GM layers."""
    slug = story["meta"]["slug"]
    uni = _store().get("storycfg:universal") or {}
    mine = _store().get(f"storycfg:{slug}") or {}
    universal = None
    if _as_bool(mine.get("use_universal"), True):
        universal = (uni.get("text") or "").strip() or UNIVERSAL_GM_DEFAULT
    dm = (mine.get("dm_guide") or "").strip() \
        or (story["meta"].get("dm_guide") or "").strip() or None
    return universal, dm


def refresh_prompt(system, session=None):
    """Re-render + re-activate the chat's story prompt — the live tuning
    loop: saving GM settings lands on the very next turn."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return False
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return True


def _manifest_prompts():
    """The plugin's shipped pack files (base for dynamic re-registration)."""
    monoliths, pieces = {}, {}
    try:
        monoliths = json.loads((_PLUGIN_DIR / "prompts" / "monoliths.json").read_text(encoding="utf-8"))
    except Exception as e:
        logger.warning(f"[STORY] monoliths.json unreadable: {e}")
    try:
        pieces = json.loads((_PLUGIN_DIR / "prompts" / "pieces.json").read_text(encoding="utf-8"))
    except Exception as e:
        logger.warning(f"[STORY] pieces.json unreadable: {e}")
    monoliths.update(st.get_dynamic())  # restart-proof rendered story prompts
    return monoliths, pieces


def _local_ctx(local_name):
    """Actor pieces from the chosen local prompt: assembled preset → its
    character/relationship pieces (clean interleave); monolith → whole text
    as the face (graceful degrade — can't split a monolith)."""
    ctx = {"name": local_name, "character_key": None, "character_text": None,
           "relationship_text": None, "monolith_text": None}
    if not local_name:
        return ctx
    try:
        from core.prompt_manager import prompt_manager
        comps = prompt_manager.components
        preset = (getattr(prompt_manager, "scenario_presets", {}) or {}).get(local_name)
        if preset:
            ck = preset.get("character")
            if ck:
                ctx["character_key"] = ck
                ctx["character_text"] = comps.get("character", {}).get(ck)
            rk = preset.get("relationship")
            if rk:
                ctx["relationship_text"] = comps.get("relationship", {}).get(rk)
        if not ctx["character_text"]:
            from core import prompts as core_prompts
            data = core_prompts.get_prompt(local_name)
            if isinstance(data, dict):
                ctx["monolith_text"] = (data.get("content") or "").strip() or None
    except Exception as e:
        logger.warning(f"[STORY] local prompt '{local_name}' context failed: {e}")
    return ctx


def _chat_suffix(chat):
    # Keep '-' too: dropping it would fold 'story-chat' and 'storychat'
    # back into one costume — the collision this scoping exists to kill.
    return ("".join(c for c in str(chat).lower().replace(" ", "_")
                    if c.isalnum() or c in "_-") or "chat")


def _prompt_name_for(story, mode, chat):
    """Dynamic monolith name, PLAYTHROUGH-scoped: 'rose@titanic_2' (Krem's
    ruling 2026-08-05). The old story-wide key ('rose') meant two
    playthroughs of one story shared a single rendered costume — B's render
    overwrote A's, and B's end() unregistered A's costume mid-story.
    Pre-existing runs are untouched: entry['prompt_name'] always wins in
    _register_prompt, so old saves keep their old key."""
    slug = story["meta"]["slug"]
    suffix = _chat_suffix(chat)
    role_name = ((story["meta"].get("role") or {}).get("name") or "").strip()
    if mode in ("story", "combined") and role_name:
        cand = "".join(c for c in role_name.lower().replace(" ", "_")
                       if c.isalnum() or c == "_")
        if cand:
            cand = f"{cand}@{suffix}"
            if cand in st.get_dynamic():
                return cand                      # already ours (resume/restart)
            try:
                from core import prompts as core_prompts
                if not core_prompts.get_prompt(cand):
                    return cand
            except Exception:
                pass
            logger.info(f"[STORY] prompt name '{cand}' taken by a user prompt — using story_{slug}")
    return f"story_{slug}@{suffix}"


def _prompt_is_private(name):
    """Does this prompt carry the privacy send-gate? (monolith flag or
    preset _privacy_required)."""
    if not name:
        return False
    try:
        from core.prompt_manager import prompt_manager
        mono = prompt_manager.monoliths.get(name)
        if isinstance(mono, dict):
            return bool(mono.get("privacy_required", False))
        preset = (getattr(prompt_manager, "scenario_presets", {}) or {}).get(name)
        if isinstance(preset, dict):
            return bool(preset.get("_privacy_required", False))
    except Exception as e:
        logger.warning(f"[STORY] privacy lookup for prompt {name!r} failed: {e}")
    return False


def _inherits_privacy(entry):
    """The rendered story prompt inherits the send-gate of any prompt whose
    TEXT it embeds. In local/combined mode the local persona's own words go
    into the monolith — hardcoding privacy_required=False there silently
    stripped a private persona's gate, and end() kept the unflagged copy
    registered forever (finding 2.10)."""
    if (entry or {}).get("mode") not in ("local", "combined"):
        return False
    return _prompt_is_private((entry or {}).get("local"))


def _register_prompt(story, state, entry, chat):
    """Re-register the plugin's pack with the story's rendered prompt as a
    dynamic monolith — ASSEMBLED per the playthrough's identity mode
    (story/local/combined, entry fields) + story-owned location/scenario/
    format + live emotions/extras. Cache bust on change is ACCEPTED
    (ruling 2026-07-13)."""
    from core import prompt_packs
    from core.prompt_manager import prompt_manager
    entry = entry or {}
    monoliths, pieces = _manifest_prompts()
    slug = story["meta"]["slug"]
    mode = entry.get("mode")
    # Vault gate (vault recon finding 7): local/combined modes extract the
    # LOCAL prompt's character text and save_dynamic persists the rendered
    # costume to a PLAINTEXT sidecar that re-merges every boot — decrypted
    # vault text would survive lock and reboots. One gate here covers all
    # five callers, including _set_mode re-pointing a RUNNING story.
    # Pure 'story' mode (total swap, no local text) stays allowed.
    if mode in ("local", "combined") and entry.get("local"):
        try:
            from core.prompt_crud import is_vault_prompt
            _is_vault = is_vault_prompt(entry["local"])
        except Exception:
            _is_vault = False
        if _is_vault:
            raise ValueError(
                f"Story mode can't carry vault prompts yet — "
                f"'{entry['local']}' lives in the encrypted vault and the "
                f"story engine persists rendered prompts in plaintext. "
                f"Pick a non-vault prompt, or use 'story' identity mode.")
    local_ctx = _local_ctx(entry.get("local")) if entry.get("local") else None
    rendered = render.story_prompt(story, state, prompt_manager.components,
                                   character=entry.get("character"),
                                   mode=mode, local_ctx=local_ctx,
                                   conduct=conduct_for(story))
    name = entry.get("prompt_name") or _prompt_name_for(story, mode or "local", chat)
    private = _inherits_privacy(entry)
    st.save_dynamic(name, rendered, privacy_required=private)
    monoliths[name] = {"content": rendered, "privacy_required": private}
    prompt_packs.register_pack(PLUGIN_NAME, monoliths=monoliths, pieces=pieces)
    return name


def default_character():
    """Best default: the character of the pre-story assembled preset if any,
    else 'sapphire', else the first character piece."""
    from core import prompts
    from core.prompt_manager import prompt_manager
    chars = prompt_manager.components.get("character", {})
    try:
        active = prompts.get_active_preset_name()
        preset = prompt_manager.scenario_presets.get(active)
        if preset and preset.get("character") in chars:
            return preset["character"]
    except Exception:
        pass
    if "sapphire" in chars:
        return "sapphire"
    return next(iter(chars), None)


def _restore_pack():
    """Re-register the pack: manifest files + whatever dynamic monoliths
    remain in the sidecar. Used after drop_dynamic (story_end) AND at boot
    via the plugins_ready hook (reboot-proofing active story prompts)."""
    from core import prompt_packs
    monoliths, pieces = _manifest_prompts()
    prompt_packs.register_pack(PLUGIN_NAME, monoliths=monoliths, pieces=pieces)


# ── Which chat does this call operate on? (findings 1.1 + 1.2) ──────────────
# Two callers, two truths. TOOLS + the ghost hook run inside a turn: their
# chat is core's per-turn effective chat, NOT the global active one — a phone
# call or background conversation must never tick another chat's story.
# ROUTES are a client speaking for a room it already has open: it names its
# session explicitly, because "whatever chat is active right now" is a race
# every second tab, phone turn, and daemon wins.

def _chat_name(system, session=None):
    """The chat this call operates on: an explicit session (the client knows
    its own room) else this turn's effective chat. Never the raw global
    active chat — that's the identity fiction findings 1.1/1.2 named."""
    if session:
        return session
    sm = system.llm_chat.session_manager
    eff = getattr(sm, "_effective_chat_name", None)
    return eff() if callable(eff) else sm.get_active_chat_name()


def _chat_exists(system, chat):
    return system.llm_chat.session_manager.get_settings_for(chat) is not None


def _is_live(system, chat):
    """True when `chat` is the chat this execution context actually runs in —
    the only case where global runtime stamps (system prompt, enabled tools)
    are correct. Otherwise settings are written by name and land when that
    chat next activates (story/reassert asserts them at the door)."""
    sm = system.llm_chat.session_manager
    eff = getattr(sm, "_effective_chat_name", None)
    return chat == (eff() if callable(eff) else sm.get_active_chat_name())


def _settings_for(system, chat):
    """That chat's own settings — never the global active chat's."""
    try:
        return system.llm_chat.session_manager.get_settings_for(chat) or {}
    except Exception as e:
        logger.warning(f"[STORY] settings lookup failed for '{chat}': {e}")
        return {}


def _stamp_settings(system, chat, patch, runtime_toolset=True):
    """Persist chat settings for `chat`; apply the live toolset only when
    that chat is the one running this turn."""
    sm = system.llm_chat.session_manager
    try:
        if _is_live(system, chat):
            sm.update_chat_settings(patch)
        else:
            sm.set_named_chat_settings(chat, patch)
    except Exception as e:
        logger.warning(f"[STORY] settings stamp failed for '{chat}': {e}")
    if not (runtime_toolset and _is_live(system, chat)):
        return
    try:
        system.llm_chat.function_manager.update_enabled_functions(
            [patch.get("toolset") or "all"],
            extra_toolsets=patch.get("extra_toolsets") or None)
    except Exception as e:
        logger.warning(f"[STORY] toolset runtime apply failed: {e}")


def _activate_prompt_for(system, chat, prompt_name):
    """Wear the costume. Live chat → full activation (system prompt + preset
    + settings). Another chat → record the prompt in ITS settings only; the
    live chat keeps wearing whatever it wears."""
    from core import prompts
    if _is_live(system, chat):
        return prompts.activate_prompt(prompt_name, system)
    try:
        ok = system.llm_chat.session_manager.set_named_chat_settings(
            chat, {"prompt": prompt_name})
        return bool(ok), f"Prompt '{prompt_name}' set on '{chat}' (not the live chat)"
    except Exception as e:
        return False, str(e)


def load_active(chat):
    """(story, state) for a chat's active playthrough, or (None, None).
    Generated rooms merge over canonical ones."""
    entry = st.get_active().get(chat)
    if not entry:
        return None, None
    try:
        story = rooms.load_story(entry["story"])
    except Exception as e:
        logger.warning(f"[STORY] active story '{entry.get('story')}' failed to load: {e}")
        return None, None
    story["rooms"].update(rooms.load_generated_rooms(entry["story"], chat))
    return story, st.replay(entry["story"], chat)


def start(system, slug, character=None, mode=None, local=None, session=None):
    with _lifecycle_lock:
        return _start(system, slug, character, mode, local, session)


def _start(system, slug, character, mode, local, session):
    chat = _chat_name(system, session)
    if session and not _chat_exists(system, chat):
        return f"No chat named '{chat}' — a story's session must be a real chat.", False
    if st.get_active().get(chat):
        return f"A story is already active in this chat — story_end first.", False
    story = rooms.load_story(slug)
    start_room = story["rooms"][story["meta"]["start"]]
    character = character or default_character()

    # Identity mode (ruling 2026-08-03): role ships → total swap by default;
    # no role → the local persona narrates (the classic gear).
    role = story["meta"].get("role") or {}
    mode = (mode or "").strip().lower() or ("story" if role.get("text") else "local")
    if mode not in ("story", "local", "combined"):
        return f"Unknown identity mode '{mode}' — story, local, or combined.", False
    if mode in ("story", "combined") and not role.get("text"):
        mode = "local"

    # Fresh playthrough = fresh journal; the old one archives beside it
    jp = st.journal_path(slug, chat)
    if jp.exists():
        n = 1
        while jp.with_suffix(f".run{n}.jsonl").exists():
            n += 1
        jp.rename(jp.with_suffix(f".run{n}.jsonl"))

    from core import prompts
    # Pre-story costume + cockpit come from the TARGET chat's own settings,
    # not the global active preset — a story started for another session must
    # stash that session's clothes, not the operator's (finding 1.1).
    cur = _settings_for(system, chat)
    prev_prompt = (cur.get("prompt")
                   or (prompts.get_active_preset_name() if _is_live(system, chat) else None))
    # Local persona defaults to whatever the chat was wearing pre-story
    local = local or prev_prompt

    st.set_active(chat, slug, prev_prompt)
    st.update_active(chat, character=character, mode=mode, local=local,
                     prompt_name=_prompt_name_for(story, mode, chat),
                     prev_toolset=cur.get("toolset", "all"),
                     prev_extras=cur.get("extra_toolsets") or [])

    # Stamp the story cockpit: none of hers + the referee (ruling 2026-08-03).
    # Users change it after via the sidebar; the checkbox is extra_toolsets.
    _stamp_settings(system, chat, {"toolset": "none",
                                   "extra_toolsets": [STORY_TOOLS_MODULE]})

    events = [{"event": "started", "story": slug, "room": start_room["id"], "turn": 0}]
    # Story-declared starting stats (HP, gold, ...) seed as replayable events
    for k, v in (story["meta"].get("initial_flags") or {}).items():
        events.append({"event": "state_set", "key": k, "value": v, "turn": 0})
    for ev in referee._effect_events(start_room.get("on_enter") or {}, st.initial_state()):
        ev["turn"] = 0
        events.append(ev)
    for ev in events:
        st.append(slug, chat, ev)

    state = st.replay(slug, chat)
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    ok, msg = _activate_prompt_for(system, chat, prompt_name)
    if not ok:
        logger.warning(f"[STORY] prompt activation failed: {msg}")
    title = story["meta"].get("title", slug)
    warn = ""
    try:
        enabled = (set(system.llm_chat.function_manager.get_enabled_function_names())
                   if _is_live(system, chat) else {"story_act"})
        if "story_act" not in enabled:
            warn = (" ⚠ story_act is NOT in this chat's toolset — the narrator "
                    "cannot referee until the Story Engine tools are enabled.")
    except Exception:
        pass
    who = {"story": f"a total swap — you ARE {role.get('name') or 'the role'}",
           "local": f"yourself (as '{local or character}') inside the story",
           "combined": f"'{local or character}' wearing the {role.get('name') or 'role'} mask"}[mode]
    return (f"Story '{title}' begun in {mode} mode — {who}. "
            f"Prompt '{prompt_name}' active (was '{prev_prompt}'; story_end restores it, "
            f"toolset stashed too). "
            f"Open the scene from the room details in your turn context.{warn}"), True


# ── Live seal wait (Krem 2026-08-06) ────────────────────────────────────────
# Tool calls are a pause BETWEEN provider API calls — nothing upstream waits.
# When she opens an UNFILLED seal with the player actually in the story room,
# act() blocks its threadpool thread until the player writes (or skips) the
# blank, then re-resolves and returns the REVEAL as the tool result: she opens
# the sketchbook and discovers the drawings in the same breath. Timeout or an
# empty room degrades to the shipped hold-and-retry, verbatim.
# The event loop stays free (SSE tool exec runs on an AnyIO worker), act()
# holds no locks across the wait, and the fill route lands on another thread.

_seal_waits = {}          # (chat, key) → {"event", "deadline", "cap"}
_waits_lock = threading.Lock()
_presence = {}            # chat → monotonic ts of last story-room poll
_PRESENCE_WINDOW = 30     # 2.5 ticks of the 12s poll (hidden tabs stop polling)
_WAIT_EXTEND = 60         # seconds per "More time" click
_WAIT_CAP = 600           # hard ceiling per wait, extensions included


def _stamp_presence(chat):
    if chat:
        _presence[chat] = time.monotonic()


def _present(chat):
    """True while the story room UI has polled recently. /api/cancel cannot
    reach a blocked tool, so we never block for a room nobody is watching —
    cron, ghost turns, and ask-sapphire runs all fall through to the hold."""
    return time.monotonic() - _presence.get(chat, float("-inf")) < _PRESENCE_WINDOW


def _wait_secs(story, held):
    """sealed.wait → meta.seal_wait → 120, clamped sane."""
    for v in (held.get("wait"), story["meta"].get("seal_wait")):
        try:
            if v is not None:
                return max(5, min(_WAIT_CAP, int(v)))
        except (TypeError, ValueError):
            pass
    return 120


def _wait_for_fill(slug, chat, room, target, verb, key, timeout):
    """Block until the player fills/skips this seal, the story pauses/ends,
    or the deadline passes. 1s slices; every slice replays the journal and
    asks 'is MY seal resolved?' — so a fill that landed between resolve and
    registration wakes us on the first slice, and a fill for a DIFFERENT
    seal (event set, state unchanged) just keeps waiting. The Event is only
    a hurry-up; the journal is the truth. Deadline re-read each slice so
    extend_seal_wait bumps a wait already in flight."""
    ev = threading.Event()
    now = time.monotonic()
    entry = {"event": ev, "deadline": now + timeout, "cap": now + _WAIT_CAP}
    with _waits_lock:
        _seal_waits[(chat, key)] = entry
    try:
        while True:
            state = st.replay(slug, chat)
            skipped = state.get("seal_skipped") or []
            if (referee.seal_state(state.get("seals"), room, target, verb) is not None
                    or key in skipped
                    or referee.legacy_seal_key(target, verb) in skipped):
                return True
            active = st.get_active().get(chat)
            if not active or active.get("paused"):
                return False
            with _waits_lock:
                remaining = entry["deadline"] - time.monotonic()
            if remaining <= 0:
                return False
            ev.wait(min(1.0, remaining))
            ev.clear()
    finally:
        with _waits_lock:
            _seal_waits.pop((chat, key), None)


def _signal_seals(chat):
    """fill_seal landed something for this chat — wake every wait on it.
    The woken loop re-checks its own seal against the journal, so waking
    broadly is safe and spares fill_seal any canonical/legacy key algebra."""
    with _waits_lock:
        for (c, _k), entry in _seal_waits.items():
            if c == chat:
                entry["event"].set()


def extend_seal_wait(system, key, session=None):
    """+60s on a live wait, capped at its start+600s. Returns remaining
    seconds, or None when no wait is live (the moment already passed)."""
    chat = _chat_name(system, session)
    key = str(key or "").strip().lower()
    with _waits_lock:
        entry = _seal_waits.get((chat, key))
        if not entry:
            return None
        entry["deadline"] = min(entry["deadline"] + _WAIT_EXTEND, entry["cap"])
        return max(0, int(entry["deadline"] - time.monotonic()))


def _seal_wait_payload(chat):
    """{key, remaining} for the room's live wait, or None. Drives the popup's
    countdown; the seals list already carries ask/has_fallback per key."""
    with _waits_lock:
        for (c, key), entry in _seal_waits.items():
            if c == chat:
                return {"key": key,
                        "remaining": max(0, int(entry["deadline"] - time.monotonic()))}
    return None


def _commit(system, story, slug, chat, state, events):
    """Journal a resolve's events; re-register the prompt if any of them
    touched it. Extracted from act() so the live-wait path can commit the
    held attempt and, after the wake, the reveal."""
    prompt_dirty = False
    for ev in events:
        ev["turn"] = state["turn"]
        st.append(slug, chat, ev)
        if ev["event"] in ("emotions", "extras"):
            prompt_dirty = True
    if prompt_dirty:
        fresh = st.replay(slug, chat)
        prompt_name = _register_prompt(story, fresh, st.get_active().get(chat, {}), chat)
        _activate_prompt_for(system, chat, prompt_name)


def act(system, verb, target=None, answer=None, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat. story_start begins one.", False
    if state["ended"]:
        return "This story has ended. story_end to close it out.", False
    if st.get_active().get(chat, {}).get("paused"):
        return "The story is paused (intermission) — resume it from the sidebar.", False
    room = story["rooms"].get(state["room"])
    if not room:
        return f"Current room {state['room']} is missing — author error. story_end to bail out.", False

    slug = story["meta"]["slug"]
    events, message, ok = referee.resolve(story, state, room, story["rooms"], verb, target, answer)
    _commit(system, story, slug, chat, state, events)

    # Held seal + player in the room → wait for their words, then re-resolve:
    # the reveal replaces the hold as this very tool call's result. The held
    # event is already journaled, so the popup machinery sees the reach even
    # while we block. Timeout returns the hold message untouched.
    held = next((e for e in events if e.get("event") == "seal_held"), None)
    if held and held.get("target") and _present(chat):
        if _wait_for_fill(slug, chat, room, held["target"], held["verb"],
                          held["key"], _wait_secs(story, held)):
            story, state = load_active(chat)
            room = story["rooms"].get(state["room"]) if story else None
            if room:
                events, message, ok = referee.resolve(
                    story, state, room, story["rooms"], verb, target, answer)
                _commit(system, story, slug, chat, state, events)

    return message, ok


def set_mode(system, mode=None, local=None, return_prompt=None, session=None):
    """Switch the playthrough's identity mode (story/local/combined) —
    re-renders and re-activates the prompt; toolset untouched. With only
    return_prompt given, just records which prompt story_end restores to."""
    with _lifecycle_lock:
        return _set_mode(system, mode, local, return_prompt, session)


def _set_mode(system, mode, local, return_prompt, session):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    if return_prompt is not None:
        st.update_active(chat, return_prompt=return_prompt or None)
        if not mode:
            return (f"After the story, the prompt returns to '{return_prompt}'." if return_prompt
                    else "After the story, the prompt returns to whatever this chat wore before."), True
    role = story["meta"].get("role") or {}
    mode = (mode or "").strip().lower()
    if mode not in ("story", "local", "combined"):
        return "Identity mode must be story, local, or combined.", False
    if mode in ("story", "combined") and not role.get("text"):
        return f"'{story['meta'].get('title')}' ships no role — only local mode works here.", False
    entry = st.get_active().get(chat, {})
    old_name = entry.get("prompt_name") or f"story_{story['meta']['slug']}"
    updates = {"mode": mode, "prompt_name": _prompt_name_for(story, mode, chat)}
    if local:
        updates["local"] = local
    st.update_active(chat, **updates)
    if updates["prompt_name"] != old_name:
        st.drop_dynamic(old_name)
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return f"Identity mode now '{mode}' — prompt '{prompt_name}' active.", True


def end(system, session=None):
    with _lifecycle_lock:
        return _end(system, session)


def _end(system, session):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    # Read, don't pop: active.json is cleared LAST, after the costume and
    # cockpit are actually restored. Popping first meant any throw below left
    # a dirty cockpit and an invisible save whose journal the next ▶Start
    # would archive out from under the player (finding 4.8).
    entry = st.get_active().get(chat)
    if not entry:
        return "No story is active in this chat.", False
    if story and state and not state["ended"]:
        st.append(entry["story"], chat, {"event": "ended", "turn": state["turn"]})
    story_prompt_name = entry.get("prompt_name") or f"story_{entry['story']}"
    from core import prompts
    # Checkbox semantics (Krem's ruling 2026-08-03, post-first-full-play):
    # return_prompt SET → revert to it. NOT set → STAY in the story prompt —
    # the tale leaves a wearable costume behind (dynamic monolith stays
    # registered via the sidecar; user switches prompts whenever they like).
    ret = entry.get("return_prompt")
    if ret:
        st.drop_dynamic(story_prompt_name)
        st.drop_dynamic(f"story_{entry['story']}")   # legacy key, harmless if absent
        _restore_pack()
        prev = ret if ret not in (story_prompt_name, f"story_{entry['story']}") else None
        if prev:
            ok, msg = _activate_prompt_for(system, chat, prev)
            if not ok:
                logger.warning(f"[STORY] restoring prompt '{prev}' failed: {msg}")
                prev = None
        if not prev:
            _activate_prompt_for(system, chat, "default")
        prompt_note = f"prompt restored to '{prev or 'default'}'"
    else:
        st.drop_dynamic(f"story_{entry['story']}") if f"story_{entry['story']}" != story_prompt_name else None
        _restore_pack()                              # keeps story_prompt_name registered
        prompt_note = f"prompt stays '{story_prompt_name}' — switch anytime from the sidebar"
    # Cockpit follows the SAME checkbox ruling as the costume (Krem
    # 2026-08-03, the search_memory-after-end desync): return_prompt set →
    # restore the stashed toolset+extras; not set → the story cockpit STAYS
    # (none + story tools — exactly what the sidebar says). Settings and
    # runtime move together or not at all.
    if ret and "prev_toolset" in entry:
        _stamp_settings(system, chat,
                        {"toolset": entry.get("prev_toolset") or "all",
                         "extra_toolsets": entry.get("prev_extras") or []})
    st.clear_active(chat)
    # The REAL path — the pre-2.7 hardcoded string sent her (and the player)
    # to a directory that no longer exists under the digest scheme.
    try:
        keep = rooms.save_dir(entry["story"], chat).relative_to(rooms.SAPPHIRE_ROOT)
    except Exception:
        keep = f"user/story_saves/{entry['story']}"
    return (f"Story closed. Journal kept at {keep}/ — "
            f"{prompt_note}."), True


def status(system, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        stories = rooms.list_stories()
        lines = [f"- {slug}: {meta['title']} — {meta['description']}" for slug, meta in stories.items()]
        return "No active story. Available:\n" + ("\n".join(lines) or "(none installed)"), True
    room = story["rooms"].get(state["room"])
    return (f"Story: {story['meta'].get('title')} | Turn: {state['turn']} | "
            f"Room: {room['title'] if room else state['room']} | "
            f"Inventory: {', '.join(state['inventory']) or 'empty'} | "
            f"Emotions: {', '.join(state['emotions']) or 'none'} | "
            f"Solved: {', '.join(state['solved']) or 'none'}"), True


def set_paused(system, paused, session=None):
    """Intermission: ghost block + turn ticks stop, story_act refuses; the
    story prompt STAYS active (still 'in' the story). Flag in active.json."""
    chat = _chat_name(system, session)
    if not st.update_active(chat, paused=bool(paused)):
        return "No story is active in this chat.", False
    return ("Story paused — intermission." if paused else "Story resumed."), True


def _art_url(story, filename):
    """Web URL for a file in the pack's backdrops/ dir, or None. Checks the
    file EXISTS so JSONs may declare art before it's painted (no broken
    imgs). Only plugin-band packs are web-served (images-only lane)."""
    if not filename:
        return None
    try:
        base = Path(story.get("path", ""))
        if not (base / "backdrops" / filename).is_file():
            return None
        parts = base.parts
        i = parts.index("plugins")
        plug = parts[i + 1]
        rel = "/".join(parts[i + 2:])
        return f"/plugin-web/{plug}/{rel}/backdrops/{filename}"
    except (ValueError, IndexError):
        return None


def _backdrop_url(story, room):
    return _art_url(story, (room or {}).get("backdrop"))


# ── Sealed blanks (Krem 2026-08-04) ─────────────────────────────────────────

def _due_hints(room, turns_in_room):
    """Turn-gated player hints whose gate has passed. Author-typed values are
    coerced, never trusted: a JSON string gate crashed the status route."""
    out = []
    for h in (room.get("player_hints") or []):
        if not isinstance(h, dict):
            continue
        try:
            after = int(h.get("after_turns", 0) or 0)
        except (TypeError, ValueError):
            after = 0
        if turns_in_room >= after:
            out.append(str(h.get("text") or ""))
    return out


def _room_seals(room, state):
    """The current room's sealed blanks, player-facing: what's still open
    (drives the popup), what's filled (the ✍ chip, editable), whether she
    reached for one early (held count → urgency re-raise). Hidden-and-unfound
    objects stay engine-side, same rule as everything else.

    Defensive by design: this runs inside the 12s poll, so ANY throw here
    500s the status route and freezes the whole sidebar — after which
    re-entry paints "No active story" over a story that is running fine
    (finding 3.1). A malformed pack must degrade to a missing chip, never
    to a dead room."""
    out = []
    for name, obj in referee._visible_objects(room, state).items():
        interactions = (obj or {}).get("interactions")
        if not isinstance(interactions, dict):
            continue
        for vname, vspec in interactions.items():
            s = vspec.get("sealed") if isinstance(vspec, dict) else None
            if not isinstance(s, dict):
                continue
            verb = referee._norm(vname)
            key = referee.seal_key(room, name, verb)
            filled = referee.seal_state(state.get("seals"), room, name, verb)
            skipped = state.get("seal_skipped", []) or []
            revealed = state.get("revealed", []) or []
            legacy = referee.legacy_seal_key(name, verb)
            out.append({
                "key": key, "object": name, "verb": verb,
                "ask": s.get("ask") or f"What does the {str(name).replace('_', ' ')} reveal?",
                "has_fallback": bool(s.get("fallback")),
                "filled": filled is not None,
                "text": filled,
                "skipped": key in skipped or legacy in skipped,
                "revealed": key in revealed or legacy in revealed,
                "held": referee.seal_state(state.get("seal_holds"), room, name, verb, 0),
            })
    return out


def fill_seal(system, key, text=None, skip=False, session=None):
    """The player writes (or skips) a sealed blank. Journaled like a dice
    value — at creation time; replay never re-prompts. Re-fill before the
    reveal just appends a newer event (fold takes the last)."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    key = str(key or "").strip().lower()
    # Room-scoped resolution: the old scan compared unscoped 'object:verb'
    # across EVERY room and kept the last match, so two rooms sharing an
    # object/verb pair wrote into each other (finding 3.2). Legacy unscoped
    # keys still resolve — first match wins — for saves already holding one.
    spec, legacy_spec = None, None
    for room in story["rooms"].values():
        for name, obj in (room.get("objects") or {}).items():
            # isinstance, not `or {}`: a list-valued interactions is truthy
            # and 500s the fill route (same guard _room_seals carries).
            _ix = (obj or {}).get("interactions")
            for vname, vspec in (_ix.items() if isinstance(_ix, dict) else ()):
                cand = vspec.get("sealed") if isinstance(vspec, dict) else None
                if not isinstance(cand, dict):
                    continue
                if key == referee.seal_key(room, name, vname):
                    spec = cand
                    break
                if legacy_spec is None and key == referee.legacy_seal_key(name, vname):
                    legacy_spec = cand
            if spec is not None:
                break
        if spec is not None:
            break
    spec = spec if spec is not None else legacy_spec
    if not isinstance(spec, dict):
        return f"No sealed blank named '{key}' in this story.", False
    if key in state.get("revealed", []):
        return "That reveal already happened — it's canon now.", False
    slug = story["meta"]["slug"]
    if skip:
        if not spec.get("fallback"):
            return "This blank has no author fallback — the story needs your words here.", False
        # A skip after the blank is already written used to report success
        # and do nothing — the fold takes the player's text, so the author's
        # fallback never fires (finding 3.4). Say what actually happened.
        if state.get("seals", {}).get(key) is not None:
            return ("You've already written this one — clear it from the ✍ chip if you "
                    "want the author's line instead."), False
        st.append(slug, chat, {"event": "seal_skipped", "key": key, "turn": state["turn"]})
        _signal_seals(chat)
        return "Skipped — the author's line will fire instead.", True
    text = str(text or "").strip()
    if not text:
        return "Write something — the blank is the whole point.", False
    st.append(slug, chat, {"event": "sealed", "key": key, "text": text[:2000],
                           "turn": state["turn"]})
    _signal_seals(chat)
    return "Sealed in. She'll find it when she gets there.", True


def _declared_verbs(name, obj, state):
    """Tap-to-draft verb chips for one visible object. Same isinstance guard
    as _room_seals: this runs in the 12s poll, and an author-typed
    `"interactions": 3` used to 500 the status route one line UPSTREAM of
    the 3.1 hardening (post-fix review 2026-08-05)."""
    ix = obj.get("interactions")
    verbs = {str(v).lower() for v in ix} if isinstance(ix, dict) else set()
    if obj.get("puzzle") and name not in state["solved"]:
        verbs.add("solve")
    verbs.add("look")
    return sorted(verbs)


def _ending_card_url(story, state, room):
    """First ending_cards entry whose condition matches — outcome-specific
    THE END art ({"card": "...", "condition": {...}} list on ending rooms)."""
    for c in (room or {}).get("ending_cards") or []:
        if referee.check_condition(c.get("condition"), state):
            url = _art_url(story, c.get("card"))
            if url:
                return url
    return None


def full_state(system, session=None):
    """Everything stored, for the Inspect modal — including False/None."""
    chat = _chat_name(system, session)
    # The 12s story-room poll funnels here (and stops when the tab hides) —
    # that makes this call the honest "a player is watching" signal the live
    # seal wait gates on. Browser-only path; server code never polls this.
    _stamp_presence(chat)
    story, state = load_active(chat)
    if not story:
        return None
    entry = st.get_active().get(chat, {})
    room = story["rooms"].get(state["room"])
    return {
        "story": story["meta"].get("title", story["meta"]["slug"]),
        "slug": story["meta"]["slug"],
        "mode": entry.get("mode"),
        "local": entry.get("local"),
        "prompt_name": entry.get("prompt_name"),
        "prev_prompt": entry.get("prev_prompt"),
        "return_prompt": entry.get("return_prompt"),
        "role": (story["meta"].get("role") or {}).get("name"),
        "player_role": story["meta"].get("player_role"),
        "paused": bool(entry.get("paused")),
        "room": room["title"] if room else state["room"],
        # Player-facing scene layer (Krem 2026-08-03: "the user has no idea
        # what is happening") — short spoiler-free desc + exit labels. The
        # detailed template stays AI-side in the ghost block.
        "room_desc": (room.get("player_desc") or "") if room else "",
        "room_backdrop": _backdrop_url(story, room),
        "ending_card": _ending_card_url(story, state, room),
        "room_exits": [{"label": ex.get("label"), "desc": ex.get("desc") or ""}
                       for ex in (room.get("exits") or [])] if room else [],
        # Visible interactables (hidden-and-unfound stay engine-side) and
        # turn-gated player hints — both feed the scene strip, never answers.
        "room_objects": [{"name": name, "desc": obj.get("desc") or "",
                          "puzzle": bool(obj.get("puzzle")),
                          "solved": name in state["solved"],
                          "used": name in state.get("used", []),
                          # Declared affordances — tap-to-draft in the panel.
                          # Conditions stay hidden; a gated verb refusing IS
                          # a story beat (blocked_message).
                          "verbs": _declared_verbs(name, obj, state)}
                         for name, obj in referee._visible_objects(room, state).items()]
                        if room else [],
        # A string after_turns ('3') used to raise inside the 12s poll and
        # take the whole sidebar down with it (finding 3.1).
        "player_hints": _due_hints(room, state["turns_in_room"]) if room else [],
        # Sealed blanks in THIS room — the popup + ✍ chip run on these.
        "seals": _room_seals(room, state) if room else [],
        # Live wait (she's blocked inside story_act right now): drives the
        # popup's countdown bar. ask/has_fallback come from seals[] by key.
        "seal_wait": _seal_wait_payload(chat),
        "room_id": state["room"],
        "turn": state["turn"],
        "turns_in_room": state["turns_in_room"],
        "inventory": state["inventory"],
        "emotions": state["emotions"],
        "extras": state.get("extras", []),
        "character": entry.get("character"),
        "solved": state["solved"],
        "found": state["found"],
        "flags": state["flags"],
        "blockers": referee.blockers(room, state) if room else [],
        "ended": state["ended"],
    }


def last_played(system, session=None):
    """The chat's most recent FINISHED playthrough (no story active):
    THE END must survive a browser refresh, and the journal is the source of
    truth — replay recovers the final room, flags, and thus the earned
    ending card. (Krem 2026-08-03: 'expected to see the outcome background')."""
    chat = _chat_name(system, session)
    if not chat or st.get_active().get(chat):
        return None
    best = None
    for slug in rooms.list_stories():
        try:
            jp = st.journal_path(slug, chat)
            if jp.exists():
                m = jp.stat().st_mtime
                if best is None or m > best[1]:
                    best = (slug, m)
        except Exception:
            continue
    if not best:
        return None
    slug = best[0]
    try:
        story = rooms.load_story(slug)
        story["rooms"].update(rooms.load_generated_rooms(slug, chat))
        state = st.replay(slug, chat)
        room = story["rooms"].get(state["room"])
        return {
            "story": story["meta"].get("title", slug), "slug": slug,
            "room": room["title"] if room else state["room"],
            "room_id": state["room"], "ended": True,
            "room_backdrop": _backdrop_url(story, room),
            "ending_card": _ending_card_url(story, state, room),
        }
    except Exception as e:
        logger.warning(f"[STORY] last_played('{slug}') failed: {e}")
        return None


def revert(system, turn, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    slug = story["meta"]["slug"]
    dropped = st.truncate(slug, chat, int(turn))
    fresh = st.replay(slug, chat)
    prompt_name = _register_prompt(story, fresh, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return f"Reverted to turn {turn} — {dropped} event(s) archived off the timeline.", True
