# gameroom_story/session.py — orchestration: start/act/end, prompt
# registration, chat activation. One active story per chat; the chat IS the
# playthrough. (Moved from the story_engine plugin 2026-08-03 — the game-room
# host owns both gears now; prompt pack registers under game-room.)
import json
import logging
import threading
import time
from pathlib import Path

from . import rooms, state as st, referee, render

logger = logging.getLogger(__name__)

_PLUGIN_DIR = Path(__file__).parent.parent
PLUGIN_NAME = "game-room"

# The referee's function module as the core registry names it — unioned into
# any toolset via the chat's `extra_toolsets` list (the "include story tools"
# checkbox). Story default: toolset 'none' + this (Krem's ruling 2026-08-03).
STORY_TOOLS_MODULE = "plugin_game-room_story_tools"

# The dual-layer GM conduct (Krem's ruling 2026-08-03: NO hidden
# instructions — conduct is user-editable and shows in the 👁 preview).
# Layer 1: this universal GM style, shared by ALL stories, toggleable per
# story. Layer 2: a per-story DM guide the pack ships, user override wins.
UNIVERSAL_GM_DEFAULT = (
    "We run this story as a team: the player drives their character; I bring the world "
    "and everyone else in it. Every turn I make sure the player knows what's around us "
    "and what they can do — exits, objects, people worth talking to — woven into my "
    "narration, not a menu. I use story_act to resolve actions: the player's when they "
    "choose them, my own character's small moves when it's natural — but I never spend "
    "the player's big choices for them or push us onward before they've had their say. "
    "I assist their intent, faithfully: when their wording is a SYNONYM for a declared "
    "verb ('drink the champagne' where the room says 'toast' — same act, different word), "
    "I use the declared verb on their behalf. But when their intent is genuinely DIFFERENT "
    "from everything declared (throwing the bracelet into the sea is not returning it), I "
    "never force a mapping — off-script acts are welcome: I play them out in the narration, "
    "honestly, with consequences in the fiction, and the tracked world simply doesn't "
    "change. Better an improvised scene than a betrayed intent. "
    "The engine referees; I narrate its verdicts truthfully and keep the machinery invisible. "
    "Each turn, a bracketed 'system context' block arrives alongside the player's message — "
    "that is my own app's dashboard (time, story state, room details), generated by my "
    "system, not written by the player and not an outside voice. I expect it, I trust it, "
    "and I never mistake it for a trick.")

_cfg_store = None

# One lifecycle op at a time. start/end/set_mode each read active.json,
# rename a journal, and re-register a prompt — a double-clicked ▶ Start ran
# two of those interleaved and the second archived the journal the first had
# just created (finding 4.12). Cheap: these are user-paced operations.
_lifecycle_lock = threading.RLock()


def _store():
    global _cfg_store
    if _cfg_store is None:
        # Loader singleton — a bare PluginState here would be a second
        # whole-file snapshot fighting gameroom_core's (finding 0.3).
        from core.plugin_loader import plugin_loader
        _cfg_store = plugin_loader.get_plugin_state(PLUGIN_NAME)
    return _cfg_store


def _as_bool(v, default=True):
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    return str(v).strip().lower() not in ("false", "0", "no", "off", "")


def conduct_for(story):
    """(universal_text | None, dm_guide | None) — the two GM layers."""
    slug = story["meta"]["slug"]
    uni = _store().get("storycfg:universal") or {}
    mine = _store().get(f"storycfg:{slug}") or {}
    universal = None
    if _as_bool(mine.get("use_universal"), True):
        universal = (uni.get("text") or "").strip() or UNIVERSAL_GM_DEFAULT
    dm = (mine.get("dm_guide") or "").strip() \
        or (story["meta"].get("dm_guide") or "").strip() or None
    return universal, dm


def refresh_prompt(system, session=None):
    """Re-render + re-activate the chat's story prompt — the live tuning
    loop: saving GM settings lands on the very next turn."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return False
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return True


def _manifest_prompts():
    """The plugin's shipped pack files (base for dynamic re-registration)."""
    monoliths, pieces = {}, {}
    try:
        monoliths = json.loads((_PLUGIN_DIR / "prompts" / "monoliths.json").read_text(encoding="utf-8"))
    except Exception as e:
        logger.warning(f"[STORY] monoliths.json unreadable: {e}")
    try:
        pieces = json.loads((_PLUGIN_DIR / "prompts" / "pieces.json").read_text(encoding="utf-8"))
    except Exception as e:
        logger.warning(f"[STORY] pieces.json unreadable: {e}")
    # Restart-proof rendered story prompts. The sealed filter (P3-T16) is
    # STRUCTURAL now: costumes live on their chat's plugin_chat_data row,
    # and core's cross-chat read omits hidden chats — a locked chat's
    # costume name can't surface in the global prompt list, and the next
    # unlocked read re-merges it. (v1.3 cutover, 2026-08-15.)
    dyn = st.get_dynamic()
    monoliths.update(dyn)
    return monoliths, pieces


def _local_ctx(local_name):
    """Actor pieces from the chosen local prompt: assembled preset → its
    character/relationship pieces (clean interleave); monolith → whole text
    as the face (graceful degrade — can't split a monolith)."""
    ctx = {"name": local_name, "character_key": None, "character_text": None,
           "relationship_text": None, "monolith_text": None}
    if not local_name:
        return ctx
    try:
        from core.prompt_manager import prompt_manager
        comps = prompt_manager.components
        preset = (getattr(prompt_manager, "scenario_presets", {}) or {}).get(local_name)
        if preset:
            ck = preset.get("character")
            if ck:
                ctx["character_key"] = ck
                ctx["character_text"] = comps.get("character", {}).get(ck)
            rk = preset.get("relationship")
            if rk:
                ctx["relationship_text"] = comps.get("relationship", {}).get(rk)
        if not ctx["character_text"]:
            from core import prompts as core_prompts
            data = core_prompts.get_prompt(local_name)
            if isinstance(data, dict):
                ctx["monolith_text"] = (data.get("content") or "").strip() or None
    except Exception as e:
        logger.warning(f"[STORY] local prompt '{local_name}' context failed: {e}")
    return ctx


def _chat_suffix(chat):
    # Keep '-' too: dropping it would fold 'story-chat' and 'storychat'
    # back into one costume — the collision this scoping exists to kill.
    return ("".join(c for c in str(chat).lower().replace(" ", "_")
                    if c.isalnum() or c in "_-") or "chat")


def _prompt_name_for(story, mode, chat):
    """Dynamic monolith name, PLAYTHROUGH-scoped: 'rose@titanic_2' (Krem's
    ruling 2026-08-05). The old story-wide key ('rose') meant two
    playthroughs of one story shared a single rendered costume — B's render
    overwrote A's, and B's end() unregistered A's costume mid-story.
    Pre-existing runs are untouched: entry['prompt_name'] always wins in
    _register_prompt, so old saves keep their old key."""
    slug = story["meta"]["slug"]
    suffix = _chat_suffix(chat)
    role_name = ((story["meta"].get("role") or {}).get("name") or "").strip()
    if mode in ("story", "combined") and role_name:
        cand = "".join(c for c in role_name.lower().replace(" ", "_")
                       if c.isalnum() or c == "_")
        if cand:
            cand = f"{cand}@{suffix}"
            if cand in st.get_dynamic():
                return cand                      # already ours (resume/restart)
            try:
                from core import prompts as core_prompts
                if not core_prompts.get_prompt(cand):
                    return cand
            except Exception:
                pass
            logger.info(f"[STORY] prompt name '{cand}' taken by a user prompt — using story_{slug}")
    return f"story_{slug}@{suffix}"


def _prompt_is_private(name):
    """Does this prompt carry the privacy send-gate? (monolith flag or
    preset _privacy_required)."""
    if not name:
        return False
    try:
        from core.prompt_manager import prompt_manager
        mono = prompt_manager.monoliths.get(name)
        if isinstance(mono, dict):
            return bool(mono.get("privacy_required", False))
        preset = (getattr(prompt_manager, "scenario_presets", {}) or {}).get(name)
        if isinstance(preset, dict):
            return bool(preset.get("_privacy_required", False))
    except Exception as e:
        logger.warning(f"[STORY] privacy lookup for prompt {name!r} failed: {e}")
    return False


def _inherits_privacy(entry, chat=None):
    """The rendered story prompt inherits the send-gate of any prompt whose
    TEXT it embeds. In local/combined mode the local persona's own words go
    into the monolith — hardcoding privacy_required=False there silently
    stripped a private persona's gate, and end() kept the unflagged copy
    registered forever (finding 2.10). The session CHAT's own private flag
    inherits too (hunt 2026-08-17): a private playthrough's rendered story
    text is private content whatever identity mode it runs in — without
    this, pure story mode registered it unflagged and any public chat
    could wear it to a cloud provider."""
    if chat:
        try:
            from core.api_fastapi import get_system
            s = get_system().llm_chat.session_manager.get_settings_for(chat)
            if isinstance(s, dict) and s.get("private_chat"):
                return True
        except Exception:
            pass
    if (entry or {}).get("mode") not in ("local", "combined"):
        return False
    return _prompt_is_private((entry or {}).get("local"))


def _register_prompt(story, state, entry, chat):
    """Re-register the plugin's pack with the story's rendered prompt as a
    dynamic monolith — ASSEMBLED per the playthrough's identity mode
    (story/local/combined, entry fields) + story-owned location/scenario/
    format + live emotions/extras. Cache bust on change is ACCEPTED
    (ruling 2026-07-13)."""
    from core import prompt_packs
    from core.prompt_manager import prompt_manager
    entry = entry or {}
    monoliths, pieces = _manifest_prompts()
    slug = story["meta"]["slug"]
    mode = entry.get("mode")
    # Vault gate (vault recon finding 7): local/combined modes extract the
    # LOCAL prompt's character text into the rendered costume. Since v1.3
    # the costume is a chat-scoped ROW — but on a PUBLIC story chat that
    # row is plaintext, so decrypted vault text would still leave the
    # vault. Possible relaxation (needs a ruling): allow when the session
    # chat is private/vaulted, since the row seals with it. One gate here
    # covers all five callers, including _set_mode re-pointing a RUNNING
    # story. Pure 'story' mode (total swap, no local text) stays allowed.
    if mode in ("local", "combined") and entry.get("local"):
        try:
            from core.prompt_crud import is_vault_prompt
            _is_vault = is_vault_prompt(entry["local"])
        except Exception:
            _is_vault = False
        if _is_vault:
            raise ValueError(
                f"Story mode can't carry vault prompts yet — "
                f"'{entry['local']}' lives in the encrypted vault and the "
                f"story engine persists rendered prompts in plaintext. "
                f"Pick a non-vault prompt, or use 'story' identity mode.")
    local_ctx = _local_ctx(entry.get("local")) if entry.get("local") else None
    rendered = render.story_prompt(story, state, prompt_manager.components,
                                   character=entry.get("character"),
                                   mode=mode, local_ctx=local_ctx,
                                   conduct=conduct_for(story))
    name = entry.get("prompt_name") or _prompt_name_for(story, mode or "local", chat)
    private = _inherits_privacy(entry, chat=chat)
    st.save_dynamic(name, rendered, privacy_required=private, chat=chat)
    monoliths[name] = {"content": rendered, "privacy_required": private,
                       "kind": "story"}
    prompt_packs.register_pack(PLUGIN_NAME, monoliths=monoliths, pieces=pieces,
                               kind="internal")
    return name


def default_character():
    """Best default: the character of the pre-story assembled preset if any,
    else 'sapphire', else the first character piece."""
    from core import prompts
    from core.prompt_manager import prompt_manager
    chars = prompt_manager.components.get("character", {})
    try:
        active = prompts.get_active_preset_name()
        preset = prompt_manager.scenario_presets.get(active)
        if preset and preset.get("character") in chars:
            return preset["character"]
    except Exception:
        pass
    if "sapphire" in chars:
        return "sapphire"
    return next(iter(chars), None)


def _restore_pack():
    """Re-register the pack: manifest files + whatever dynamic monoliths
    remain in the sidecar. Used after drop_dynamic (story_end) AND at boot
    via the plugins_ready hook (reboot-proofing active story prompts)."""
    from core import prompt_packs
    monoliths, pieces = _manifest_prompts()
    prompt_packs.register_pack(PLUGIN_NAME, monoliths=monoliths, pieces=pieces,
                               kind="internal")


# ── Which chat does this call operate on? (findings 1.1 + 1.2) ──────────────
# Two callers, two truths. TOOLS + the ghost hook run inside a turn: their
# chat is core's per-turn effective chat, NOT the global active one — a phone
# call or background conversation must never tick another chat's story.
# ROUTES are a client speaking for a room it already has open: it names its
# session explicitly, because "whatever chat is active right now" is a race
# every second tab, phone turn, and daemon wins.

def _chat_name(system, session=None):
    """The chat this call operates on: an explicit session (the client knows
    its own room) else this turn's effective chat. Never the raw global
    active chat — that's the identity fiction findings 1.1/1.2 named."""
    if session:
        return session
    sm = system.llm_chat.session_manager
    eff = getattr(sm, "_effective_chat_name", None)
    return eff() if callable(eff) else sm.get_active_chat_name()


def _chat_exists(system, chat):
    return system.llm_chat.session_manager.get_settings_for(chat) is not None


def _is_live(system, chat):
    """True when `chat` is the chat this execution context actually runs in —
    the only case where global runtime stamps (system prompt, enabled tools)
    are correct. Otherwise settings are written by name and land when that
    chat next activates (story/reassert asserts them at the door)."""
    sm = system.llm_chat.session_manager
    eff = getattr(sm, "_effective_chat_name", None)
    return chat == (eff() if callable(eff) else sm.get_active_chat_name())


def _settings_for(system, chat):
    """That chat's own settings — never the global active chat's."""
    try:
        return system.llm_chat.session_manager.get_settings_for(chat) or {}
    except Exception as e:
        logger.warning(f"[STORY] settings lookup failed for '{chat}': {e}")
        return {}


def _stamp_settings(system, chat, patch, runtime_toolset=True):
    """Persist chat settings for `chat`; apply the live toolset only when
    that chat is the one running this turn."""
    sm = system.llm_chat.session_manager
    try:
        if _is_live(system, chat):
            sm.update_chat_settings(patch)
        else:
            sm.set_named_chat_settings(chat, patch)
    except Exception as e:
        logger.warning(f"[STORY] settings stamp failed for '{chat}': {e}")
    if not (runtime_toolset and _is_live(system, chat)):
        return
    try:
        system.llm_chat.function_manager.update_enabled_functions(
            [patch.get("toolset") or "all"],
            extra_toolsets=patch.get("extra_toolsets") or None)
    except Exception as e:
        logger.warning(f"[STORY] toolset runtime apply failed: {e}")


def _activate_prompt_for(system, chat, prompt_name):
    """Wear the costume. Live chat → full activation (system prompt + preset
    + settings). Another chat → record the prompt in ITS settings only; the
    live chat keeps wearing whatever it wears."""
    from core import prompts
    if _is_live(system, chat):
        return prompts.activate_prompt(prompt_name, system)
    try:
        ok = system.llm_chat.session_manager.set_named_chat_settings(
            chat, {"prompt": prompt_name})
        return bool(ok), f"Prompt '{prompt_name}' set on '{chat}' (not the live chat)"
    except Exception as e:
        return False, str(e)


def load_active(chat):
    """(story, state) for a chat's active playthrough, or (None, None).
    Generated rooms merge over canonical ones; then the playthrough's user
    layer (placed objects + room-text overrides) and Mad-Libs slot
    substitution — ONE seam, so the referee, the ghost block, full_state,
    and the seal scans all see the same world (plan tmp/open-mansion-plan.md
    keystones K1/K2)."""
    entry = st.get_active().get(chat)
    if not entry:
        return None, None
    try:
        story = rooms.load_story(entry["story"])
    except Exception as e:
        logger.warning(f"[STORY] active story '{entry.get('story')}' failed to load: {e}")
        return None, None
    story["rooms"].update(rooms.load_generated_rooms(entry["story"], chat))
    state = st.replay(entry["story"], chat)
    _merge_user_layer(story, entry["story"], chat, state)
    _apply_slots(story, entry.get("slots") or {})
    return story, state


def _merge_user_layer(story, slug, chat, state):
    """K1 — merge once, at load. User-placed objects join the room dicts.
    Shadow law (2026-08-20, editor v2): a user entry matching a SHIPPED
    name is a deliberate override — `{"_removed": true}` tombstones the
    shipped object; `{"_replace": true, ...}` swaps it wholesale (the
    editor's fidelity-gate lane); anything else field-merges over it (desc/hidden
    replace; interactions overlay per-verb, replacing only `message` so
    shipped mechanics — effects, seals, dice, conditions — survive a
    reword). New names add wholesale, carrying their own per-object
    `condition` (stamped at set-import for non-shipped names), checked by
    the referee's visibility funnel — no gating here. Exits follow the same
    law (shadow + additive, ungated — F2 2026-08-21). Room TEXT overrides
    alone stay zork-gated (meta.open_flag; no flag declared = no line =
    apply always)."""
    try:
        data = st.get_user_layer(slug, chat)
    except Exception as e:
        logger.warning(f"[STORY] user layer read failed for '{slug}': {e}")
        return
    if not data:
        return
    for rid, objs in (data.get("objects") or {}).items():
        try:
            room = story["rooms"].get(int(rid))
        except (TypeError, ValueError):
            room = None
        if not room or not isinstance(objs, dict):
            continue
        target = room.setdefault("objects", {})
        for name, spec in objs.items():
            if not isinstance(spec, dict):
                continue
            if spec.get("_removed"):
                target.pop(name, None)
                continue
            # Fidelity-gate lane (2026-08-21): a _replace entry swaps the
            # shipped object WHOLESALE — machinery included ({} strips it
            # to nothing but what the entry carries). Editor-only marker;
            # the field-merge below stays the law for plain shadows.
            if spec.get("_replace"):
                target[name] = {k: v for k, v in spec.items() if k != "_replace"}
                continue
            if name in target and isinstance(target[name], dict):
                base = dict(target[name])
                if "desc" in spec:
                    base["desc"] = spec["desc"]
                if "hidden" in spec:
                    base["hidden"] = bool(spec["hidden"])
                ints = dict(base.get("interactions") or {})
                for verb, vspec in (spec.get("interactions") or {}).items():
                    if not isinstance(vspec, dict):
                        continue
                    if verb in ints and isinstance(ints[verb], dict):
                        merged = dict(ints[verb])
                        if "message" in vspec:
                            merged["message"] = vspec["message"]
                        ints[verb] = merged
                    else:
                        ints[verb] = vspec
                if ints:
                    base["interactions"] = ints
                target[name] = base
                continue
            target[name] = spec
    # Exits (exits editor, 2026-08-21) — UNGATED like objects (F2, the
    # clown_key law: no implicit zork stamps; authors gate explicitly via
    # visible_when). exit_shadows field-merge over the shipped exit with
    # matching `to` (label/desc/blocked_message replace; shipped mechanics
    # ride UNLESS the shadow carries a `mechanics` unit, which replaces
    # them wholesale — {} strips the door bare); {"_removed": true} walls
    # the door off. add_exits append, dedup by destination, enriched
    # fields (condition/roll/effects/visible_when) verbatim.
    for rid, txt in (data.get("rooms") or {}).items():
        try:
            room = story["rooms"].get(int(rid))
        except (TypeError, ValueError):
            room = None
        if not room or not isinstance(txt, dict):
            continue
        shadows = txt.get("exit_shadows") or {}
        if shadows and room.get("exits"):
            kept = []
            for ex in room["exits"]:
                sh = shadows.get(str(ex.get("to"))) if isinstance(ex, dict) else None
                if not isinstance(sh, dict):
                    kept.append(ex)
                    continue
                if sh.get("_removed"):
                    continue
                merged = dict(ex)
                for f in ("label", "desc", "blocked_message"):
                    if str(sh.get(f) or "").strip():
                        merged[f] = str(sh[f])
                mech = sh.get("mechanics")
                if isinstance(mech, dict):
                    for f in ("condition", "roll", "effects", "visible_when"):
                        merged.pop(f, None)
                        if isinstance(mech.get(f), dict) and mech[f]:
                            merged[f] = mech[f]
                kept.append(merged)
            room["exits"] = kept
        have = {e.get("to") for e in (room.get("exits") or []) if isinstance(e, dict)}
        for ex in (txt.get("add_exits") or []):
            if isinstance(ex, dict) and ex.get("to") not in have:
                room.setdefault("exits", []).append(dict(ex))
                have.add(ex.get("to"))
    # Room TEXT overrides stay zork-gated: pre-open, the shipped tutorial
    # corridor reads as shipped (a different animal from user CONTENT).
    open_flag = (story["meta"].get("open_flag") or "").strip()
    if open_flag and not state["flags"].get(open_flag):
        return
    for rid, txt in (data.get("rooms") or {}).items():
        try:
            room = story["rooms"].get(int(rid))
        except (TypeError, ValueError):
            room = None
        if not room or not isinstance(txt, dict):
            continue
        if str(txt.get("template") or "").strip():
            room["template"] = str(txt["template"])
        if str(txt.get("player_desc") or "").strip():
            room["player_desc"] = str(txt["player_desc"])


def _apply_slots(story, slots):
    """K2 — substitute once, at load: {slot_key} tokens in the story's meta
    text and every string a room dict carries. Values are brace-stripped at
    start, so a slot can't smuggle {ai_name} into core's later template
    pass. Role name/text substitute too — the assembled-setup-as-role pattern
    (_start substitutes before prompt-name derivation, so the costume's
    registered name comes from the RESOLVED role name). Title stays literal."""
    vals = {k: str(v) for k, v in (slots or {}).items() if str(v).strip()}
    if not vals:
        return

    def sub(text):
        for k, v in vals.items():
            text = text.replace("{" + k + "}", v)
        return text

    def walk(node):
        if isinstance(node, str):
            return sub(node) if "{" in node else node
        if isinstance(node, dict):
            return {k: walk(v) for k, v in node.items()}
        if isinstance(node, list):
            return [walk(v) for v in node]
        return node

    meta = story["meta"]
    if isinstance(meta.get("role"), dict):
        r = dict(meta["role"])
        for f in ("name", "text"):
            if r.get(f):
                r[f] = sub(r[f])
        meta["role"] = r
    for f in ("premise", "player_role", "dm_guide"):
        if isinstance(meta.get(f), str) and "{" in meta[f]:
            meta[f] = sub(meta[f])
    for rid in list(story["rooms"]):
        story["rooms"][rid] = walk(story["rooms"][rid])


def _clean_slots(story, slots):
    """Submitted slot values → validated dict. Unknown keys drop; declared-
    but-missing slots take their defaults so no raw {token} ever reaches
    her prompt. Sealed slots ride the seal machinery, never substitution."""
    out = {}
    for decl in rooms.story_slots(story["meta"]):
        if decl["sealed"]:
            continue
        v = str((slots or {}).get(decl["key"], "")).strip() or decl["default"]
        v = v.replace("{", "").replace("}", "")[:1000].strip()
        if v:
            out[decl["key"]] = v
    return out


def start(system, slug, character=None, mode=None, local=None, session=None,
          slots=None):
    with _lifecycle_lock:
        return _start(system, slug, character, mode, local, session,
                      slots=slots)


def _apply_scenario_env(chat, slug, story, name):
    """PURE SWAP (Krem's ruling 2026-08-20): the playthrough's environment
    BECOMES the named scenario — canvas = snapshot, VERBATIM. Empty name =
    reset to the shipped-only house. No implicit zork-line stamp anymore
    (clown_key finding, same day): under swap the scenario IS the house
    from turn 0 — what you saw when you saved is what you get when you
    load. At-open materialization is the author's explicit choice via a
    Visible-when condition on the object."""
    if not name:
        st.save_user_layer(slug, chat, {"objects": {}, "rooms": {},
                                        "scenario": ""})
        return
    sets = _store().get(f"storyscenarios:{slug}") or {}
    data = sets.get(name)
    if not isinstance(data, dict):
        raise KeyError(name)
    objects = {}
    for rid, objs in (data.get("objects") or {}).items():
        if not isinstance(objs, dict):
            continue
        cur = {}
        for oname, spec in objs.items():
            if not isinstance(spec, dict):
                continue
            spec = dict(spec)
            spec.setdefault("_author", "player")
            cur[oname] = spec
        if cur:
            objects[str(rid)] = cur
    rooms_ov = {str(rid): txt for rid, txt in (data.get("rooms") or {}).items()
                if isinstance(txt, dict)}
    st.save_user_layer(slug, chat, {"objects": objects, "rooms": rooms_ov,
                                    "scenario": name})


def _start(system, slug, character, mode, local, session, slots=None):
    chat = _chat_name(system, session)
    if session and not _chat_exists(system, chat):
        return f"No chat named '{chat}' — a story's session must be a real chat.", False
    # Ruling F1 refusal LIFTED (v1.3, 2026-08-15): journals/costumes live
    # on the chat's plugin_chat_data rows and seal with it — private chats
    # host stories now. The HIDDEN gate (sealed vault) still refuses via
    # the store's own write raise + the P3 seat rails.
    if st.get_active().get(chat):
        return f"A story is already active in this chat — story_end first.", False
    story = rooms.load_story(slug)
    start_room = story["rooms"][story["meta"]["start"]]
    character = character or default_character()

    # Slots substitute BEFORE identity/mode/prompt-name derivation — a story
    # may assemble its whole role from the setup form (role.name/text as
    # slot tokens; Krem's ruling 2026-08-20: the setup popup IS the
    # assembled prompt, registered as the story costume).
    slot_vals = _clean_slots(story, slots)
    _apply_slots(story, slot_vals)

    # Identity mode (ruling 2026-08-03): role ships → total swap by default;
    # no role → the local persona narrates (the classic gear).
    role = story["meta"].get("role") or {}
    mode = (mode or "").strip().lower() or ("story" if role.get("text") else "local")
    if mode not in ("story", "local", "combined"):
        return f"Unknown identity mode '{mode}' — story, local, or combined.", False
    if mode in ("story", "combined") and not role.get("text"):
        mode = "local"

    # Fresh playthrough = fresh journal; the old one archives beside it
    st.new_run(slug, chat)

    from core import prompts
    # Pre-story costume + cockpit come from the TARGET chat's own settings,
    # not the global active preset — a story started for another session must
    # stash that session's clothes, not the operator's (finding 1.1).
    cur = _settings_for(system, chat)
    prev_prompt = (cur.get("prompt")
                   or (prompts.get_active_preset_name() if _is_live(system, chat) else None))
    # Local persona defaults to whatever the chat was wearing pre-story
    local = local or prev_prompt

    st.set_active(chat, slug, prev_prompt)
    st.update_active(chat, character=character, mode=mode, local=local,
                     prompt_name=_prompt_name_for(story, mode, chat),
                     prev_toolset=cur.get("toolset", "all"),
                     prev_extras=cur.get("extra_toolsets") or [],
                     slots=slot_vals)
    # (Scenario ENV swaps happen via story/scenarios/load — applied the
    # moment the setup form's dropdown changes; no start-time param.)

    # Stamp the story cockpit: none of hers + the referee (ruling 2026-08-03).
    # Users change it after via the sidebar; the checkbox is extra_toolsets.
    _stamp_settings(system, chat, {"toolset": "none",
                                   "extra_toolsets": [STORY_TOOLS_MODULE]})

    events = [{"event": "started", "story": slug, "room": start_room["id"], "turn": 0}]
    # Story-declared starting stats (HP, gold, ...) seed as replayable events
    for k, v in (story["meta"].get("initial_flags") or {}).items():
        events.append({"event": "state_set", "key": k, "value": v, "turn": 0})
    for ev in referee._effect_events(start_room.get("on_enter") or {}, st.initial_state()):
        ev["turn"] = 0
        events.append(ev)
    for ev in events:
        st.append(slug, chat, ev)

    state = st.replay(slug, chat)
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    ok, msg = _activate_prompt_for(system, chat, prompt_name)
    if not ok:
        logger.warning(f"[STORY] prompt activation failed: {msg}")
    title = story["meta"].get("title", slug)
    warn = ""
    try:
        enabled = (set(system.llm_chat.function_manager.get_enabled_function_names())
                   if _is_live(system, chat) else {"story_act"})
        if "story_act" not in enabled:
            warn = (" ⚠ story_act is NOT in this chat's toolset — the narrator "
                    "cannot referee until the Story Engine tools are enabled.")
    except Exception:
        pass
    who = {"story": f"a total swap — you ARE {role.get('name') or 'the role'}",
           "local": f"yourself (as '{local or character}') inside the story",
           "combined": f"'{local or character}' wearing the {role.get('name') or 'role'} mask"}[mode]
    return (f"Story '{title}' begun in {mode} mode — {who}. "
            f"Prompt '{prompt_name}' active (was '{prev_prompt}'; story_end restores it, "
            f"toolset stashed too). "
            f"Open the scene from the room details in your turn context.{warn}"), True


# ── Live seal wait (Krem 2026-08-06) ────────────────────────────────────────
# Tool calls are a pause BETWEEN provider API calls — nothing upstream waits.
# When she opens an UNFILLED seal with the player actually in the story room,
# act() blocks its threadpool thread until the player writes (or skips) the
# blank, then re-resolves and returns the REVEAL as the tool result: she opens
# the sketchbook and discovers the drawings in the same breath. Timeout or an
# empty room degrades to the shipped hold-and-retry, verbatim.
# The event loop stays free (SSE tool exec runs on an AnyIO worker), act()
# holds no locks across the wait, and the fill route lands on another thread.

_seal_waits = {}          # (chat, key) → {"event", "deadline", "cap"}
_waits_lock = threading.Lock()
_presence = {}            # chat → monotonic ts of last story-room poll
_PRESENCE_WINDOW = 30     # 2.5 ticks of the 12s poll (hidden tabs stop polling)
_WAIT_EXTEND = 60         # seconds per "More time" click
_WAIT_CAP = 600           # hard ceiling per wait, extensions included


def _stamp_presence(chat):
    if chat:
        _presence[chat] = time.monotonic()


def _present(chat):
    """True while the story room UI has polled recently. /api/cancel cannot
    reach a blocked tool, so we never block for a room nobody is watching —
    cron, ghost turns, and ask-sapphire runs all fall through to the hold."""
    return time.monotonic() - _presence.get(chat, float("-inf")) < _PRESENCE_WINDOW


def _wait_secs(story, held):
    """sealed.wait → meta.seal_wait → 120, clamped sane."""
    for v in (held.get("wait"), story["meta"].get("seal_wait")):
        try:
            if v is not None:
                return max(5, min(_WAIT_CAP, int(v)))
        except (TypeError, ValueError):
            pass
    return 120


def _wait_for_fill(slug, chat, room, target, verb, key, timeout):
    """Block until the player fills/skips this seal, the story pauses/ends,
    or the deadline passes. 1s slices; every slice replays the journal and
    asks 'is MY seal resolved?' — so a fill that landed between resolve and
    registration wakes us on the first slice, and a fill for a DIFFERENT
    seal (event set, state unchanged) just keeps waiting. The Event is only
    a hurry-up; the journal is the truth. Deadline re-read each slice so
    extend_seal_wait bumps a wait already in flight."""
    ev = threading.Event()
    now = time.monotonic()
    entry = {"event": ev, "deadline": now + timeout, "cap": now + _WAIT_CAP}
    with _waits_lock:
        _seal_waits[(chat, key)] = entry
    try:
        while True:
            state = st.replay(slug, chat)
            skipped = state.get("seal_skipped") or []
            if (referee.seal_state(state.get("seals"), room, target, verb) is not None
                    or key in skipped
                    or referee.legacy_seal_key(target, verb) in skipped):
                return True
            active = st.get_active().get(chat)
            if not active or active.get("paused"):
                return False
            with _waits_lock:
                remaining = entry["deadline"] - time.monotonic()
            if remaining <= 0:
                return False
            ev.wait(min(1.0, remaining))
            ev.clear()
    finally:
        with _waits_lock:
            _seal_waits.pop((chat, key), None)


def _signal_seals(chat):
    """fill_seal landed something for this chat — wake every wait on it.
    The woken loop re-checks its own seal against the journal, so waking
    broadly is safe and spares fill_seal any canonical/legacy key algebra."""
    with _waits_lock:
        for (c, _k), entry in _seal_waits.items():
            if c == chat:
                entry["event"].set()


def extend_seal_wait(system, key, session=None):
    """+60s on a live wait, capped at its start+600s. Returns remaining
    seconds, or None when no wait is live (the moment already passed)."""
    chat = _chat_name(system, session)
    key = str(key or "").strip().lower()
    with _waits_lock:
        entry = _seal_waits.get((chat, key))
        if not entry:
            return None
        entry["deadline"] = min(entry["deadline"] + _WAIT_EXTEND, entry["cap"])
        return max(0, int(entry["deadline"] - time.monotonic()))


def _seal_wait_payload(chat):
    """{key, remaining} for the room's live wait, or None. Drives the popup's
    countdown; the seals list already carries ask/has_fallback per key."""
    with _waits_lock:
        for (c, key), entry in _seal_waits.items():
            if c == chat:
                return {"key": key,
                        "remaining": max(0, int(entry["deadline"] - time.monotonic()))}
    return None


def _commit(system, story, slug, chat, state, events):
    """Journal a resolve's events; re-register the prompt if any of them
    touched it. Extracted from act() so the live-wait path can commit the
    held attempt and, after the wake, the reveal."""
    prompt_dirty = False
    for ev in events:
        ev["turn"] = state["turn"]
        st.append(slug, chat, ev)
        if ev["event"] in ("emotions", "extras"):
            prompt_dirty = True
    if prompt_dirty:
        fresh = st.replay(slug, chat)
        prompt_name = _register_prompt(story, fresh, st.get_active().get(chat, {}), chat)
        _activate_prompt_for(system, chat, prompt_name)


def act(system, verb, target=None, answer=None, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat. story_start begins one.", False
    if state["ended"]:
        return "This story has ended. story_end to close it out.", False
    if st.get_active().get(chat, {}).get("paused"):
        return "The story is paused (intermission) — resume it from the sidebar.", False
    room = story["rooms"].get(state["room"])
    if not room:
        return f"Current room {state['room']} is missing — author error. story_end to bail out.", False

    slug = story["meta"]["slug"]
    events, message, ok = referee.resolve(story, state, room, story["rooms"], verb, target, answer)
    _commit(system, story, slug, chat, state, events)

    # Held seal + player in the room → wait for their words, then re-resolve:
    # the reveal replaces the hold as this very tool call's result. The held
    # event is already journaled, so the popup machinery sees the reach even
    # while we block. Timeout returns the hold message untouched.
    held = next((e for e in events if e.get("event") == "seal_held"), None)
    if held and held.get("target") and _present(chat):
        if _wait_for_fill(slug, chat, room, held["target"], held["verb"],
                          held["key"], _wait_secs(story, held)):
            story, state = load_active(chat)
            room = story["rooms"].get(state["room"]) if story else None
            if room:
                events, message, ok = referee.resolve(
                    story, state, room, story["rooms"], verb, target, answer)
                _commit(system, story, slug, chat, state, events)

    return message, ok


def set_mode(system, mode=None, local=None, return_prompt=None, session=None):
    """Switch the playthrough's identity mode (story/local/combined) —
    re-renders and re-activates the prompt; toolset untouched. With only
    return_prompt given, just records which prompt story_end restores to."""
    with _lifecycle_lock:
        return _set_mode(system, mode, local, return_prompt, session)


def _set_mode(system, mode, local, return_prompt, session):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    if return_prompt is not None:
        st.update_active(chat, return_prompt=return_prompt or None)
        if not mode:
            return (f"After the story, the prompt returns to '{return_prompt}'." if return_prompt
                    else "After the story, the prompt returns to whatever this chat wore before."), True
    role = story["meta"].get("role") or {}
    mode = (mode or "").strip().lower()
    if mode not in ("story", "local", "combined"):
        return "Identity mode must be story, local, or combined.", False
    if mode in ("story", "combined") and not role.get("text"):
        return f"'{story['meta'].get('title')}' ships no role — only local mode works here.", False
    entry = st.get_active().get(chat, {})
    old_name = entry.get("prompt_name") or f"story_{story['meta']['slug']}"
    updates = {"mode": mode, "prompt_name": _prompt_name_for(story, mode, chat)}
    if local:
        updates["local"] = local
    st.update_active(chat, **updates)
    if updates["prompt_name"] != old_name:
        st.drop_dynamic(old_name)
    prompt_name = _register_prompt(story, state, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return f"Identity mode now '{mode}' — prompt '{prompt_name}' active.", True


def end(system, session=None):
    with _lifecycle_lock:
        return _end(system, session)


def _end(system, session):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    # Read, don't pop: active.json is cleared LAST, after the costume and
    # cockpit are actually restored. Popping first meant any throw below left
    # a dirty cockpit and an invisible save whose journal the next ▶Start
    # would archive out from under the player (finding 4.8).
    entry = st.get_active().get(chat)
    if not entry:
        return "No story is active in this chat.", False
    if story and state and not state["ended"]:
        st.append(entry["story"], chat, {"event": "ended", "turn": state["turn"]})
    story_prompt_name = entry.get("prompt_name") or f"story_{entry['story']}"
    from core import prompts
    # Checkbox semantics (Krem's ruling 2026-08-03, post-first-full-play):
    # return_prompt SET → revert to it. NOT set → the ROOM's return prompt
    # (sidebar default, 2026-08-21) if configured, else STAY in the story
    # prompt — the tale leaves a wearable costume behind (dynamic monolith
    # stays registered; user switches prompts whenever they like).
    ret = entry.get("return_prompt") or _room_return_prompt() or None
    if ret:
        st.drop_dynamic(story_prompt_name)
        st.drop_dynamic(f"story_{entry['story']}")   # legacy key, harmless if absent
        _restore_pack()
        prev = ret if ret not in (story_prompt_name, f"story_{entry['story']}") else None
        if prev:
            ok, msg = _activate_prompt_for(system, chat, prev)
            if not ok:
                logger.warning(f"[STORY] restoring prompt '{prev}' failed: {msg}")
                prev = None
        if not prev:
            _activate_prompt_for(system, chat, "default")
        prompt_note = f"prompt restored to '{prev or 'default'}'"
    else:
        st.drop_dynamic(f"story_{entry['story']}") if f"story_{entry['story']}" != story_prompt_name else None
        _restore_pack()                              # keeps story_prompt_name registered
        prompt_note = f"prompt stays '{story_prompt_name}' — switch anytime from the sidebar"
    # Cockpit follows the SAME checkbox ruling as the costume (Krem
    # 2026-08-03, the search_memory-after-end desync): return_prompt set →
    # restore the stashed toolset+extras; not set → the story cockpit STAYS
    # (none + story tools — exactly what the sidebar says). Settings and
    # runtime move together or not at all.
    if ret and "prev_toolset" in entry:
        _stamp_settings(system, chat,
                        {"toolset": entry.get("prev_toolset") or "all",
                         "extra_toolsets": entry.get("prev_extras") or []})
    st.clear_active(chat)
    # v1.3: the journal lives on this chat's rows now — kept until the chat
    # itself is deleted, sealed if the chat is.
    return (f"Story closed. Journal kept with this chat — "
            f"{prompt_note}."), True


def status(system, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        stories = rooms.list_stories()
        lines = [f"- {slug}: {meta['title']} — {meta['description']}" for slug, meta in stories.items()]
        return "No active story. Available:\n" + ("\n".join(lines) or "(none installed)"), True
    room = story["rooms"].get(state["room"])
    return (f"Story: {story['meta'].get('title')} | Turn: {state['turn']} | "
            f"Room: {room['title'] if room else state['room']} | "
            f"Inventory: {', '.join(state['inventory']) or 'empty'} | "
            f"Emotions: {', '.join(state['emotions']) or 'none'} | "
            f"Solved: {', '.join(state['solved']) or 'none'}"), True


def _room_return_prompt():
    """The room-wide return prompt (Game Room sidebar, Krem 2026-08-21):
    who the chat becomes on pause, and the default after end. '' = the old
    behavior (costume stays / end's stay-in-costume ruling)."""
    try:
        import gameroom_core as gc
        return (gc.room_config().get('return_prompt') or '').strip()
    except Exception:
        return ""


def set_paused(system, paused, session=None):
    """Intermission: ghost block + turn ticks stop, story_act refuses.
    With a room return-prompt configured, pausing also hands the chat back
    to that persona — talk to your own Sapphire mid-story — and resuming
    re-dresses the story costume (the reassert law). No prompt configured =
    the costume stays on, as before (Krem's ruling 2026-08-21)."""
    chat = _chat_name(system, session)
    if not st.update_active(chat, paused=bool(paused)):
        return "No story is active in this chat.", False
    ret = _room_return_prompt()
    if paused and ret:
        ok, msg = _activate_prompt_for(system, chat, ret)
        if ok:
            return f"Story paused — intermission (back to '{ret}').", True
        logger.warning(f"[STORY] pause return-prompt '{ret}' failed: {msg}")
    if not paused:
        try:
            refresh_prompt(system, session=session)
        except Exception as e:
            logger.warning(f"[STORY] resume costume re-assert failed: {e}")
    return ("Story paused — intermission." if paused else "Story resumed."), True


def _art_url(story, filename):
    """Web URL for a file in the pack's backdrops/ dir, or None. Checks the
    file EXISTS so JSONs may declare art before it's painted (no broken
    imgs). Only plugin-band packs are web-served (images-only lane)."""
    if not filename:
        return None
    try:
        base = Path(story.get("path", ""))
        if not (base / "backdrops" / filename).is_file():
            return None
        parts = base.parts
        i = parts.index("plugins")
        plug = parts[i + 1]
        rel = "/".join(parts[i + 2:])
        return f"/plugin-web/{plug}/{rel}/backdrops/{filename}"
    except (ValueError, IndexError):
        return None


def _backdrop_url(story, room):
    return _art_url(story, (room or {}).get("backdrop"))


# ── Sealed blanks (Krem 2026-08-04) ─────────────────────────────────────────

def _due_hints(room, turns_in_room):
    """Turn-gated player hints whose gate has passed. Author-typed values are
    coerced, never trusted: a JSON string gate crashed the status route."""
    out = []
    for h in (room.get("player_hints") or []):
        if not isinstance(h, dict):
            continue
        try:
            after = int(h.get("after_turns", 0) or 0)
        except (TypeError, ValueError):
            after = 0
        if turns_in_room >= after:
            out.append(str(h.get("text") or ""))
    return out


def _room_seals(room, state):
    """The current room's sealed blanks, player-facing: what's still open
    (drives the popup), what's filled (the ✍ chip, editable), whether she
    reached for one early (held count → urgency re-raise). Hidden-and-unfound
    objects stay engine-side, same rule as everything else.

    Defensive by design: this runs inside the 12s poll, so ANY throw here
    500s the status route and freezes the whole sidebar — after which
    re-entry paints "No active story" over a story that is running fine
    (finding 3.1). A malformed pack must degrade to a missing chip, never
    to a dead room."""
    out = []
    for name, obj in referee._visible_objects(room, state).items():
        interactions = (obj or {}).get("interactions")
        if not isinstance(interactions, dict):
            continue
        for vname, vspec in interactions.items():
            s = vspec.get("sealed") if isinstance(vspec, dict) else None
            if not isinstance(s, dict):
                continue
            verb = referee._norm(vname)
            key = referee.seal_key(room, name, verb)
            filled = referee.seal_state(state.get("seals"), room, name, verb)
            skipped = state.get("seal_skipped", []) or []
            revealed = state.get("revealed", []) or []
            legacy = referee.legacy_seal_key(name, verb)
            out.append({
                "key": key, "object": name, "verb": verb,
                "ask": s.get("ask") or f"What does the {str(name).replace('_', ' ')} reveal?",
                "has_fallback": bool(s.get("fallback")),
                "filled": filled is not None,
                "text": filled,
                "skipped": key in skipped or legacy in skipped,
                "revealed": key in revealed or legacy in revealed,
                "held": referee.seal_state(state.get("seal_holds"), room, name, verb, 0),
            })
    return out


def fill_seal(system, key, text=None, skip=False, session=None):
    """The player writes (or skips) a sealed blank. Journaled like a dice
    value — at creation time; replay never re-prompts. Re-fill before the
    reveal just appends a newer event (fold takes the last)."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    key = str(key or "").strip().lower()
    # Room-scoped resolution: the old scan compared unscoped 'object:verb'
    # across EVERY room and kept the last match, so two rooms sharing an
    # object/verb pair wrote into each other (finding 3.2). Legacy unscoped
    # keys still resolve — first match wins — for saves already holding one.
    spec, legacy_spec = None, None
    for room in story["rooms"].values():
        for name, obj in (room.get("objects") or {}).items():
            # isinstance, not `or {}`: a list-valued interactions is truthy
            # and 500s the fill route (same guard _room_seals carries).
            _ix = (obj or {}).get("interactions")
            for vname, vspec in (_ix.items() if isinstance(_ix, dict) else ()):
                cand = vspec.get("sealed") if isinstance(vspec, dict) else None
                if not isinstance(cand, dict):
                    continue
                if key == referee.seal_key(room, name, vname):
                    spec = cand
                    break
                if legacy_spec is None and key == referee.legacy_seal_key(name, vname):
                    legacy_spec = cand
            if spec is not None:
                break
        if spec is not None:
            break
    spec = spec if spec is not None else legacy_spec
    if not isinstance(spec, dict):
        return f"No sealed blank named '{key}' in this story.", False
    if key in state.get("revealed", []):
        return "That reveal already happened — it's canon now.", False
    slug = story["meta"]["slug"]
    if skip:
        if not spec.get("fallback"):
            return "This blank has no author fallback — the story needs your words here.", False
        # A skip after the blank is already written used to report success
        # and do nothing — the fold takes the player's text, so the author's
        # fallback never fires (finding 3.4). Say what actually happened.
        if state.get("seals", {}).get(key) is not None:
            return ("You've already written this one — clear it from the ✍ chip if you "
                    "want the author's line instead."), False
        st.append(slug, chat, {"event": "seal_skipped", "key": key, "turn": state["turn"]})
        _signal_seals(chat)
        return "Skipped — the author's line will fire instead.", True
    text = str(text or "").strip()
    if not text:
        return "Write something — the blank is the whole point.", False
    st.append(slug, chat, {"event": "sealed", "key": key, "text": text[:2000],
                           "turn": state["turn"]})
    _signal_seals(chat)
    return "Sealed in. She'll find it when she gets there.", True


def _declared_verbs(name, obj, state):
    """Tap-to-draft verb chips for one visible object. Same isinstance guard
    as _room_seals: this runs in the 12s poll, and an author-typed
    `"interactions": 3` used to 500 the status route one line UPSTREAM of
    the 3.1 hardening (post-fix review 2026-08-05)."""
    ix = obj.get("interactions")
    verbs = {str(v).lower() for v in ix} if isinstance(ix, dict) else set()
    if obj.get("puzzle") and name not in state["solved"]:
        verbs.add("solve")
    verbs.add("look")
    return sorted(verbs)


def _ending_card_url(story, state, room):
    """First ending_cards entry whose condition matches — outcome-specific
    THE END art ({"card": "...", "condition": {...}} list on ending rooms)."""
    for c in (room or {}).get("ending_cards") or []:
        if referee.check_condition(c.get("condition"), state):
            url = _art_url(story, c.get("card"))
            if url:
                return url
    return None


def full_state(system, session=None):
    """Everything stored, for the Inspect modal — including False/None."""
    chat = _chat_name(system, session)
    # Sealed-vault gate (P3-T9): a hidden session answers exactly like a
    # nonexistent one — this funnel serves status AND inspect, which
    # otherwise hand back the full state (sealed-blank text, whole prompt)
    # for any chat name the caller supplies.
    try:
        if system and system.llm_chat.session_manager.is_chat_hidden(chat):
            return None
    except Exception:
        pass
    # The 12s story-room poll funnels here (and stops when the tab hides) —
    # that makes this call the honest "a player is watching" signal the live
    # seal wait gates on. Browser-only path; server code never polls this.
    _stamp_presence(chat)
    story, state = load_active(chat)
    if not story:
        return None
    entry = st.get_active().get(chat, {})
    room = story["rooms"].get(state["room"])
    _open_flag = (story["meta"].get("open_flag") or "").strip()
    return {
        "story": story["meta"].get("title", story["meta"]["slug"]),
        "slug": story["meta"]["slug"],
        # Mad-Libs layer (open-mansion v1): this run's slot values, the
        # zork-line flag, and whether the house has opened.
        "slots": entry.get("slots") or {},
        "open_flag": _open_flag,
        "house_open": (not _open_flag) or bool(state["flags"].get(_open_flag)),
        "mode": entry.get("mode"),
        "local": entry.get("local"),
        "prompt_name": entry.get("prompt_name"),
        "prev_prompt": entry.get("prev_prompt"),
        "return_prompt": entry.get("return_prompt"),
        "role": (story["meta"].get("role") or {}).get("name"),
        "player_role": story["meta"].get("player_role"),
        "paused": bool(entry.get("paused")),
        "room": room["title"] if room else state["room"],
        # Player-facing scene layer (Krem 2026-08-03: "the user has no idea
        # what is happening") — short spoiler-free desc + exit labels. The
        # detailed template stays AI-side in the ghost block.
        "room_desc": (room.get("player_desc") or "") if room else "",
        "room_backdrop": _backdrop_url(story, room),
        "ending_card": _ending_card_url(story, state, room),
        "room_exits": [{"label": ex.get("label"), "desc": ex.get("desc") or ""}
                       for ex in referee.visible_exits(room, state)] if room else [],
        # Visible interactables (hidden-and-unfound stay engine-side) and
        # turn-gated player hints — both feed the scene strip, never answers.
        "room_objects": [{"name": name, "desc": obj.get("desc") or "",
                          "puzzle": bool(obj.get("puzzle")),
                          "solved": name in state["solved"],
                          "used": name in state.get("used", []),
                          # Declared affordances — tap-to-draft in the panel.
                          # Conditions stay hidden; a gated verb refusing IS
                          # a story beat (blocked_message).
                          "verbs": _declared_verbs(name, obj, state)}
                         for name, obj in referee._visible_objects(room, state).items()]
                        if room else [],
        # A string after_turns ('3') used to raise inside the 12s poll and
        # take the whole sidebar down with it (finding 3.1).
        "player_hints": _due_hints(room, state["turns_in_room"]) if room else [],
        # Sealed blanks in THIS room — the popup + ✍ chip run on these.
        "seals": _room_seals(room, state) if room else [],
        # Live wait (she's blocked inside story_act right now): drives the
        # popup's countdown bar. ask/has_fallback come from seals[] by key.
        "seal_wait": _seal_wait_payload(chat),
        "room_id": state["room"],
        "turn": state["turn"],
        "turns_in_room": state["turns_in_room"],
        "inventory": state["inventory"],
        "emotions": state["emotions"],
        "extras": state.get("extras", []),
        "character": entry.get("character"),
        "solved": state["solved"],
        "found": state["found"],
        "flags": state["flags"],
        "blockers": referee.blockers(room, state) if room else [],
        "ended": state["ended"],
    }


def last_played(system, session=None):
    """The chat's most recent FINISHED playthrough (no story active):
    THE END must survive a browser refresh, and the journal is the source of
    truth — replay recovers the final room, flags, and thus the earned
    ending card. (Krem 2026-08-03: 'expected to see the outcome background')."""
    chat = _chat_name(system, session)
    if not chat or st.get_active().get(chat):
        return None
    # Sealed-vault gate (P3-T9): a hidden chat's finished playthrough
    # (ending card, story title) answers like it never happened.
    try:
        if system and system.llm_chat.session_manager.is_chat_hidden(chat):
            return None
    except Exception:
        pass
    best = None
    for slug in rooms.list_stories():
        try:
            meta = st.journal_meta(slug, chat)
            # ISO timestamps compare lexicographically — same clock wrote them
            if meta and (best is None or meta["updated_at"] > best[1]):
                best = (slug, meta["updated_at"])
        except Exception:
            continue
    if not best:
        return None
    slug = best[0]
    try:
        story = rooms.load_story(slug)
        story["rooms"].update(rooms.load_generated_rooms(slug, chat))
        state = st.replay(slug, chat)
        room = story["rooms"].get(state["room"])
        return {
            "story": story["meta"].get("title", slug), "slug": slug,
            "room": room["title"] if room else state["room"],
            "room_id": state["room"], "ended": True,
            "room_backdrop": _backdrop_url(story, room),
            "ending_card": _ending_card_url(story, state, room),
        }
    except Exception as e:
        logger.warning(f"[STORY] last_played('{slug}') failed: {e}")
        return None


def update_slots(system, slots, session=None):
    """Edit the RUNNING playthrough's slot values (the gear's Setup tab) —
    re-cleans against the declarations and re-bakes the costume, so the
    change lands on her very next turn."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    st.update_active(chat, slots=_clean_slots(story, slots))
    try:
        refresh_prompt(system, session=chat)
    except Exception as e:
        logger.warning(f"[STORY] slot refresh failed: {e}")
    return "Setup updated — it lands on her next turn.", True


# ── User layer CRUD (open-mansion v1) — routes + the AI's placement tool ────

_OBJ_CAP = 80          # per playthrough — sanity, not a feature
_OBJ_BYTES = 8192      # per object spec


def upsert_user_object(chat, slug, room_id, name, spec, author="player"):
    """Place/update one authored object in the playthrough's user layer.
    Soft validation only — the referee is already defensive about every
    field it reads; we cap size/count and stamp authorship."""
    name = str(name or "").strip()
    if not name:
        return "Object needs a name.", False
    if not isinstance(spec, dict):
        return "Object spec must be an object.", False
    try:
        if len(json.dumps(spec)) > _OBJ_BYTES:
            return f"Object too large ({_OBJ_BYTES // 1024}KB cap).", False
    except (TypeError, ValueError):
        return "Object spec isn't JSON-serializable.", False
    spec = dict(spec)
    spec["_author"] = str(author)
    layer = st.get_user_layer(slug, chat)
    objects = dict(layer.get("objects") or {})
    room_objs = dict(objects.get(str(room_id)) or {})
    total = sum(len(v) for v in objects.values() if isinstance(v, dict))
    if name not in room_objs and total >= _OBJ_CAP:
        return f"Placed-object cap reached ({_OBJ_CAP} per playthrough).", False
    room_objs[name] = spec
    objects[str(room_id)] = room_objs
    st.save_user_layer(slug, chat, {"objects": objects,
                                    "rooms": layer.get("rooms") or {},
                                    "scenario": layer.get("scenario") or ""})
    return f"'{name}' placed.", True


def delete_user_object(chat, slug, room_id, name):
    layer = st.get_user_layer(slug, chat)
    objects = dict(layer.get("objects") or {})
    room_objs = dict(objects.get(str(room_id)) or {})
    if name not in room_objs:
        return "No placed object by that name in that room.", False
    room_objs.pop(name)
    if room_objs:
        objects[str(room_id)] = room_objs
    else:
        objects.pop(str(room_id), None)
    st.save_user_layer(slug, chat, {"objects": objects,
                                    "rooms": layer.get("rooms") or {},
                                    "scenario": layer.get("scenario") or ""})
    return f"'{name}' removed.", True


def set_room_text(chat, slug, room_id, template=None, player_desc=None,
                  add_exits=None):
    """Store per-room text overrides + user-added exits. Empty/whitespace
    text clears that field (routes apply verbatim-equals-shipped upstream,
    same house rule as story settings); an empty add_exits list clears the
    exits. None = leave that field as stored."""
    layer = st.get_user_layer(slug, chat)
    rooms_ov = dict(layer.get("rooms") or {})
    cur = dict(rooms_ov.get(str(room_id)) or {})
    if template is not None:
        cur["template"] = str(template)
    if player_desc is not None:
        cur["player_desc"] = str(player_desc)
    if add_exits is not None:
        cur["add_exits"] = list(add_exits)
    cur = _prune_room_layer(cur)
    if cur:
        rooms_ov[str(room_id)] = cur
    else:
        rooms_ov.pop(str(room_id), None)
    st.save_user_layer(slug, chat, {"objects": layer.get("objects") or {},
                                    "rooms": rooms_ov,
                                    "scenario": layer.get("scenario") or ""})
    return "Room saved.", True


def _prune_room_layer(cur):
    """Drop empty fields from one room's layer dict: text by strip,
    exit containers by truthiness (empty list/dict = gone)."""
    return {k: v for k, v in cur.items()
            if (v if k in ("add_exits", "exit_shadows") else str(v).strip())}


def _mutate_room_layer(chat, slug, room_id, mutate):
    """Load the layer, apply mutate(cur) to one room's dict, prune, save —
    the one write path for exit storage (scenario tag rides, same as the
    object savers)."""
    layer = st.get_user_layer(slug, chat)
    rooms_ov = dict(layer.get("rooms") or {})
    cur = dict(rooms_ov.get(str(room_id)) or {})
    mutate(cur)
    cur = _prune_room_layer(cur)
    if cur:
        rooms_ov[str(room_id)] = cur
    else:
        rooms_ov.pop(str(room_id), None)
    st.save_user_layer(slug, chat, {"objects": layer.get("objects") or {},
                                    "rooms": rooms_ov,
                                    "scenario": layer.get("scenario") or ""})


def set_user_exit(chat, slug, room_id, to, spec):
    """Upsert one user-added exit (exits editor, 2026-08-21). Enriched
    fields (condition/roll/effects/visible_when/blocked_message) ride
    verbatim — the referee is defensive about every field it reads. Keyed
    by destination: one user exit per (room, to)."""
    if not isinstance(spec, dict):
        return "Exit spec must be an object.", False
    try:
        if len(json.dumps(spec)) > _OBJ_BYTES:
            return f"Exit too large ({_OBJ_BYTES // 1024}KB cap).", False
    except (TypeError, ValueError):
        return "Exit spec isn't JSON-serializable.", False
    def mutate(cur):
        ax = [e for e in (cur.get("add_exits") or [])
              if isinstance(e, dict) and e.get("to") != to]
        ax.append(dict(spec))
        cur["add_exits"] = ax[:12]
    _mutate_room_layer(chat, slug, room_id, mutate)
    return f"Exit to room {to} saved.", True


def remove_user_exit(chat, slug, room_id, to):
    found = []
    def mutate(cur):
        ax = [e for e in (cur.get("add_exits") or []) if isinstance(e, dict)]
        kept = [e for e in ax if e.get("to") != to]
        if len(kept) != len(ax):
            found.append(True)
        cur["add_exits"] = kept
    _mutate_room_layer(chat, slug, room_id, mutate)
    if not found:
        return "No user-added exit to that room here.", False
    return "Exit removed.", True


def set_exit_shadow(chat, slug, room_id, to, shadow):
    """Shadow (or tombstone) one SHIPPED exit, keyed by destination.
    shadow = field overrides, {"_removed": True}, or None to clear the
    entry (restore to shipped)."""
    def mutate(cur):
        sh = dict(cur.get("exit_shadows") or {})
        if shadow is None:
            sh.pop(str(to), None)
        else:
            sh[str(to)] = dict(shadow)
        cur["exit_shadows"] = sh
    _mutate_room_layer(chat, slug, room_id, mutate)
    return "Exit updated.", True


def _resolve_room(story, ref, state):
    """Room by id, title (separator/case-forgiving), or current room when
    the ref is empty."""
    if ref is None or not str(ref).strip():
        return story["rooms"].get(state["room"])
    s = str(ref).strip()
    if s.isdigit():
        return story["rooms"].get(int(s))
    for room in story["rooms"].values():
        if referee._key(room.get("title")) == referee._key(s):
            return room
    return None


def place_object(system, room_ref, name, desc=None, verb=None, response=None,
                 hidden=False, session=None):
    """The AI seeds the house too (Krem's ruling 2026-08-20): an object she
    authors lands in the user layer marked _author='ai' — excluded from
    saved object sets (fork 2), otherwise a full citizen of the world."""
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    room = _resolve_room(story, room_ref, state)
    if not room:
        titles = ", ".join(f"'{r.get('title')}'" for r in story["rooms"].values())
        return f"No room matches '{room_ref}'. Rooms: {titles}.", False
    if referee._find(room.get("objects") or {}, name)[1] is not None:
        return f"Something named '{name}' is already there.", False
    spec = {"desc": str(desc or "").strip() or "something left here"}
    if hidden:
        spec["hidden"] = True
    v = referee._norm(verb or "")
    if v and v not in referee.GENERIC_VERBS:
        spec["interactions"] = {v: {"message":
                                    str(response or "").strip() or f"You {v} the {name}."}}
    slug = story["meta"]["slug"]
    msg, ok = upsert_user_object(chat, slug, room["id"], name, spec, author="ai")
    if not ok:
        return msg, False
    st.append(slug, chat, {"event": "placed", "target": str(name).strip(),
                           "room": room["id"], "turn": state["turn"]})
    return f"Placed '{name}' in {room['title']} — it's part of the world now.", True


def revert(system, turn, session=None):
    chat = _chat_name(system, session)
    story, state = load_active(chat)
    if not story:
        return "No story is active in this chat.", False
    slug = story["meta"]["slug"]
    dropped = st.truncate(slug, chat, int(turn))
    fresh = st.replay(slug, chat)
    prompt_name = _register_prompt(story, fresh, st.get_active().get(chat, {}), chat)
    _activate_prompt_for(system, chat, prompt_name)
    return f"Reverted to turn {turn} — {dropped} event(s) archived off the timeline.", True
